### PR TITLE
updating for Orchard 1.9

### PR DESCRIPTION
**Pull request by thekaveman**
This commit brings the module compatibility up to the (imminent) Orchard 1.9 release.

  - Updated Orchard version in `Module.txt`
  - .NET bumped to 4.5.1
  - `Web.config` updated accordingly
  - `Views/Web.config` no longer necessary

Tested as working with the latest [5e85d3d](http://orchard.codeplex.com/SourceControl/latest)

### CODE REVIEW

**Comment by peterkeating** [comment]
Awesome work! Will give it a quick test (although looks good) and merge it in then upload a new version to the Orchard gallery.

Thanks so much for your contribution :) Much appreciated!

**Comment by thekaveman** [comment]
Hi @peterkeating, are you still active with this module? 

We may be looking to make use of it in a few upcoming projects, targeting the latest version of Orchard (currently [`1.10`](https://github.com/OrchardCMS/Orchard/releases)). Are you interested in us sending back any modifications in the form of new PRs?

If so, I'll just close this one as we'll likely at least update for `1.10`

/cc @kevinsmgov

**Comment by peterkeating** [comment]
Hi @thekaveman @kevinsmgov,

We are still active with this module, will get your pull request integrated ASAP and then make sure the module works for `1.10`. Apologies for the slackness.

**Comment by thekaveman** [comment]
I'm closing this one in favor of #13.

**Pull request closed without merging**
